
# Services Dependencies ##
  version: '3.8'
  services:
    zookeeper:
      image: confluentinc/cp-zookeeper:latest
      container_name: zookeeper
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      hostname: zookeeper
      ports:
        - 2181:2181
    kafka-broker-1:
      image: confluentinc/cp-kafka:latest
      container_name: kafka-broker-1
      depends_on:
        - zookeeper
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka-broker-1:29092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      hostname: kafka-broker-1
      ports:
        - "9092:9092"
    kafka-ui:
      image: provectuslabs/kafka-ui:latest
      depends_on:
        - zookeeper
        - kafka-broker-1
      ports:
        - "8080:8080"
      environment:
        KAFKA_CLUSTERS_0_NAME: "My Kafka Cluster"
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka-broker-1:29092"
        KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
    postgres:
      image: postgres:latest
      container_name: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
      hostname: postgres
      ports:
        - "5432:5432"
    web:
      build:
        context: ./web-server
      container_name: web-server
      ports:
        - "3000:3000"
    producer:
      build:
        context: ./producer
      container_name: producer
      hostname: producer
      ports:
        - "4000:4000"
    consumer:
      build:
        context: ./consumer
      container_name: consumer
